import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "blogpost",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-primary  h-screen max-w-screen-xl  flex-wrap   mx-auto `}
      >
        <Navbar />
        <div>{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
